### ISSUE TITLE
AttributeError: 'GraphicsState' object has no attribute 'marker_start' on Windows10

### ISSUE THREAD

**Issue by kwyip** [xyz2tex/svg2tikz#89] opened 2023-03-04 09:38 UTC
```
Traceback (most recent call last):
  File "C:\Program Files\Inkscape\share\inkscape\extensions\tikz_export.py", line 1814, in <module>
    main_inkscape()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\tikz_export.py", line 1797, in main_inkscape
    effect.run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 231, in run
    self.save_raw(self.effect())
  File "C:\Program Files\Inkscape\share\inkscape\extensions\tikz_export.py", line 1675, in effect
    goptions, transformation = self.convert_svgstate_to_tikz(
  File "C:\Program Files\Inkscape\share\inkscape\extensions\tikz_export.py", line 1129, in convert_svgstate_to_tikz
    marker_options = self._handle_markers(state, accumulated_state)
  File "C:\Program Files\Inkscape\share\inkscape\extensions\tikz_export.py", line 1030, in _handle_markers
    if not state.marker_start and not state.marker_end:
AttributeError: 'GraphicsState' object has no attribute 'marker_start'

```

**Comment by ldevillez** [comment] 2023-03-04 17:08
Hello @kwyip,

Thanks for the bug found :)
It should be fix now. As you can see #86 was a heavy reformatting of the code so if you want you can use the tag `v1.2.0`

**Comment by kwyip** [comment] 2023-03-04 19:48
I will use the `v1.2.0` release.  In the master branch version there is also this new error after the fix above:
```
Traceback (most recent call last):
  File "C:\Program Files\Inkscape\share\inkscape\extensions\tikz_export.py", line 1814, in <module>
    main_inkscape()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\tikz_export.py", line 1797, in main_inkscape
    effect.run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 231, in run
    self.save_raw(self.effect())
  File "C:\Program Files\Inkscape\share\inkscape\extensions\tikz_export.py", line 1680, in effect
    string = self._output_group(nodes, graphics_state)
  File "C:\Program Files\Inkscape\share\inkscape\extensions\tikz_export.py", line 1638, in _output_group
    string += self._handle_group(node, graphics_state, accumulated_state)
  File "C:\Program Files\Inkscape\share\inkscape\extensions\tikz_export.py", line 1243, in _handle_group
    code = self._output_group(
  File "C:\Program Files\Inkscape\share\inkscape\extensions\tikz_export.py", line 1616, in _output_group
    pathdata, options = self._handle_path(node)
  File "C:\Program Files\Inkscape\share\inkscape\extensions\tikz_export.py", line 1313, in _handle_path
    path_punches[1][1] = self.update_height(path_punches[1][1])
IndexError: list index out of range

```

**Comment by ldevillez** [comment] 2023-03-04 20:14
Could you provide me the svg leading to this error ?

**Comment by kwyip** [comment] 2023-03-05 19:14
@ldevillez the svg is as follows. Thanks.
![pcbi 1003724 g001 (1)](https://user-images.githubusercontent.com/7807159/222980882-933d769e-59a4-4774-970a-e3b6ece4cfd4.svg)

**Comment by ldevillez** [comment] 2023-03-07 19:40
Hello @kwyip,
On your SVG, I only found a base64 image. It is really the case in your file or is it an conversion made by github ?

If it is only a base64 image inside a svg, I could not reproduce the error on Linux (So I can check on Windows) but I could fix some other things. The downside is that base64 images are not yet supported.

If it is not only a base64 image, do you think you could provide me with an non converted SVG ? :)

**Comment by ldevillez** [comment] 2023-03-28 13:40
Thanks @lytefoot I will look onto it :)
Can you tell me what is the version of svg2tikz that you used and how did you install it ?

**Comment by ldevillez** [comment] 2023-03-28 13:51
It should be good now @lytefoot (closed by #95 )

**Closed** 2023-03-28 13:50 UTC
Labels: bug

**Comment by lytefoot** [comment] 2023-03-28 13:52
I was just writing a reply when I saw you had posted a fix. This did indeed fix the issue :)

**Comment by lytefoot** [comment] 2023-03-28 14:21
Update: your fix did fix the error, but the output doesn't work correctly on any path with curves. The straight-line pentagon now exports correctly, but if I round the corners (as in [test.svg](https://user-images.githubusercontent.com/52675289/228267689-2dcd8c6f-c351-48ce-bd19-ff992454cc70.svg)), there's something very wrong with the shape tikz produces:

Intended shape:
![input svg](https://user-images.githubusercontent.com/52675289/228268133-842c5ae8-7d31-4dfb-b84f-c30121f2b018.JPG)

Actual shape:
![output tikz](https://user-images.githubusercontent.com/52675289/228267555-32554740-722d-4cb0-9ea8-8be3017d8184.JPG)

Here's the TikZ code generated:
`\path[fill=black,line width=0.026cm] (6.4182,11.8297) .. controls (-3.3460, 16.7118) and (3.1158, 25.4357) .. (4.7416, 14.6407) .. controls (6.3675, 25.8543) and (-3.4739, 13.8377) .. (7.2951, 12.0481) .. controls (18.0642, 19.4414) and (5.5201, 3.9865) .. (10.5499, 13.6755) .. controls (15.5796, 6.3355) and (17.6684, 9.4962) .. (10.0079, 17.2738) .. controls (2.3474, 4.6485) and (16.1824, 22.7524) .. (6.4182, 17.8703) -- cycle;`

It looks like something's wrong with the y-coordinates of the control points?

**Comment by ldevillez** [comment] 2023-03-29 06:56
Yeah y-coordinates can be messed up due to #85 to use the coordinate system of tikz and not inkscape. I will look into it
